name: Black Formatter
on:
  pull_request:
    branches: [main]  # Adjust this to match your main branch

jobs:
  black:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run formatter
      run: docker compose up format

    - name: Stop containers
      if: always()
      run: docker compose down
