name: Black Formatter
on:
  pull_request:
    branches: [master]  # Adjust this to match your main branch

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: build
      working-directory: ./webserver/ui
      run: npm ci
      run: npm run build

  black:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run formatter
      run: docker run --rm -v "$PWD/airflow/dags:/tmp" pyfound/black black --check /tmp

  flake8:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run formatter
        run: docker compose up lint --exit-code-from lint
